# @package _group_
common:
  fp16: false
  log_format: json
  log_interval: 200

checkpoint:
  no_epoch_checkpoints: true

task:
  _name: masked_lm
  data: ???
  sample_break_mode: complete
  tokens_per_sample: 512
  omit_mask_and_pad: true
  omit_unk: true
  mask_prob: 0.0

criterion: masked_lm

dataset:
  batch_size: 8
  ignore_unused_valid_subsets: true

optimizer:
  _name: adam
  weight_decay: 0.01
  adam_betas: (0.9,0.98)
  adam_eps: 1e-06

lr_scheduler:
  _name: polynomial_decay
  warmup_updates: 10000

optimization:
  clip_norm: 0
  lr: [0.0005]
  max_update: 125000
  update_freq: [32]

model:
  _name: roberta
  max_positions: 512
  dropout: 0.
  attention_dropout: 0.
  no_token_positional_embeddings: true
  encoder_alibi: true
  encoder_alibi_asymmetrical: true
  layernorm_embedding: false
  contrastive_pretraining: true
  initial_beta: 1.
  zero_masking: true
  mask_prob: 0.15
  vae_beta: 0.01
  initial_scale: 100.
